name: Rancher ABS
description: |
  Docker volume plugin for Aliyun Block Storage
version: 0.1.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
